export const USER_FETCH_DATA = 'USER_FETCH_DATA'
export const USER_FETCH_GROUP_DATA_EVENTS = 'USER_FETCH_GROUP_DATA_EVENTS'
export const USER_FETCH_GROUP_DATA_USERS = "USER_FETCH_GROUP_DATA_USERS"
export const USER_FETCH_GROUP_DATA_LISTINGS = "USER_FETCH_GROUP_DATA_USERS"